### ISSUE TITLE
レイアウトのバグの修正

### ISSUE THREAD

**Issue by developerhost** [developerhost/media-swap#117]
謎の余白ができているのと、背景の灰色はいらないところは消して欲しい

![screencapture-localhost-3000-add-product-2023-10-26-19_24_01](https://github.com/developerhost/media-swap/assets/50170789/9937da1d-6e63-467c-9fc1-0ae9b8d65e41)
![screencapture-swappy-jp-2023-10-26-14_43_08](https://github.com/developerhost/media-swap/assets/50170789/0b1f2a90-6e82-4bb4-a81f-f14283828a69)

**Comment by Yuki-Maeda-valour** [comment]
https://github.com/developerhost/media-swap/pull/123
