### ISSUE TITLE
devtoolsで表示がおかしくなるらしい

### ISSUE THREAD

**Issue by bmthd** [developerhost/media-swap#120]
実機再現ができないが、念のため記録

              > @developerhost @bmthd ・useMediaQuery削除(hooksディレクトリごと) ・ナビゲーションにCSSで幅が広いときdisplay:none設定 ・map関数にkey追加 上記対応完了しました。確認よろしくお願いします。 見た目の変更は変わりませんが、変わってないことの確認の為にbefore,after載せておきます。 before ![before](https://user-images.githubusercontent.com/116794108/278291751-1aa84203-23ed-4b8a-b396-587f24319645.png)
> 
> after ![after](https://user-images.githubusercontent.com/116794108/278291800-193aa04e-009a-4fe7-b10d-256538ff63db.png)

@Yuki-Maeda-valour ありがとうございます！
素晴らしいですが、一点自分の環境だけなのか遷移した時にフッターが隠れちゃうんですよね、、

これって他の人発生しないですか？

![スクリーンショット 2023-10-26 19 12 23](https://github.com/developerhost/media-swap/assets/50170789/2a040cf1-f165-4620-b9f0-19dcf102c379)

動画

https://github.com/developerhost/media-swap/assets/50170789/f8473d56-735b-40cf-98a2-64884e9e7d34

もし他の人も発生してるならできたら直して欲しいです

_Originally posted by @developerhost in https://github.com/developerhost/media-swap/issues/69#issuecomment-1780825799_

**Comment by developerhost** [comment]
@bmthd 治ったんでクローズします
