### ISSUE TITLE
vercelデプロイでたまにエラー吐くの直したい

### ISSUE THREAD

**Issue by developerhost** [developerhost/media-swap#128]

**Comment by bmthd** [comment]
先日の13.5.0のエラーログのみなのであれば以下チケットだけで対応不要かと思います。
https://github.com/developerhost/media-swap/issues/126

もし別のエラーログが出ているようであれば貼り付けて欲しいです

**Comment by developerhost** [comment]
> 先日の13.5.0のエラーログのみなのであれば以下チケットだけで対応不要かと思います。
> https://github.com/developerhost/media-swap/issues/126
> 
> もし別のエラーログが出ているようであれば貼り付けて欲しいです

@bmthd なるほど、了解です
そしたら解決したらcloseします
