### ISSUE TITLE
フッターのリンクボタンを連打したらエラーになる

### ISSUE THREAD

**Issue by developerhost** [developerhost/media-swap#130]
自分の環境だけ？
エラー修正して欲しい

![スクリーンショット 2023-10-27 17 53 41](https://github.com/developerhost/media-swap/assets/50170789/e5b9c1fb-2c80-4b8a-91bd-d14bf91d9f9d)

Application error: a client-side exception has occurred (see the browser console for more information).

![スクリーンショット 2023-10-27 18 03 28](https://github.com/developerhost/media-swap/assets/50170789/2b406c0b-38d8-4984-8611-ce26b9001ee8)

**Comment by Yuki-Maeda-valour** [comment]
10/29 バージョンアップ解消後devlopブランチにて手動で動作確認を行ったがエラーが確認できなかった為、エラー解消と判断しClose。
