### ISSUE TITLE
トップページ　出品されている商品が1つもない場合にエラーになる

### ISSUE THREAD

**Issue by bmthd** [developerhost/media-swap#135]
<img width="616" alt="image" src="https://github.com/developerhost/media-swap/assets/81406938/b6112e2a-98e9-4334-bdf7-f824300d98fd">

出品がありませんとか表示したほうが良さそう

**Comment by developerhost** [comment]
あーこれ僕も思ってました

けどサービス公開したら出品が存在しないことなんてあり得ないからサボってました。

できれば対応したいくらいの温度感です
Couldかなあ

**Comment by bmthd** [comment]
要確認

**Comment by developerhost** [comment]
できてると思われるのでクローズ
