### ISSUE TITLE
Productをbuy,sellオブジェクトも作る

### ISSUE THREAD

**Issue by developerhost** [developerhost/media-swap#15]
BuyProductオブジェクト
SellProductオブジェクト

共通部分はProductオブジェクトで持つ

- [ ] 購入済み商品には画像にsoldラベルを上に貼る
- [ ] ユーザーページから購入済み商品、取引中商品、出品商品を見れるようにする

**Comment by bmthd** [comment]
データベース設計を行い要件の整理が必要になったためクローズします
