### ISSUE TITLE
パッケージマネージャをpnpmに変えたい

### ISSUE THREAD

**Issue by bmthd** [developerhost/media-swap#160]
npmの上位互換のpnpmを入れませんか、という提案です。

## なぜ？

インストールしたことのあるパッケージは既存のインストールへのリンクになり、ダウンロードが不要になるためパッケージインストールが高速化し、PC上のストレージが節約できて開発効率が良くなります。
デプロイも早くなるし、パッケージ入れ直しのたびに30秒くらいかかってたのが5秒になります。
みんなのパソコンの容量も節約できます。

## QA
- インストールが面倒…
`npm i -g pnpm@latest`
npmにあります

- コマンド覚え直すのが嫌
VS codeならnpm scriptのところでワンクリックでコマンド実行できるので覚える必要なし

- とはいえ手打ちするでしょ？

```
npm i → pnpm i
npx * → pnpx *
```
頭にp付けるだけです

- 間違ってnpmって打ってしまいそう

間違って打ったら実行しない設定があります。

- 互換性が…
ライブラリではなくパッケージマネージャであり、pnpmもnpmからダウンロードするため、完全上位互換です。

- yarnが良いのですが
npm使ってた人はコマンド覚え直しになっちゃうので、わざわざ入れる利点が減ります。
pnpmの方が早いのでpnpmがおすすめです。

学習コストほぼなく、メリットのみを享受できるのでぜひ入れたいです。
いかがでしょうか。

**Comment by developerhost** [comment]
@bmthd デプロイ早くなるのはいいですね！！！
vercelで今npm run buildとかそこら辺走ってるんですけど、それも全く変更する必要ないんですかね？

なんか辺なエラーが出てはまってしまうとか、そういうことがないのであれば入れるのは全然問題ないです

**Comment by developerhost** [comment]
あとはnode.jsのバージョンとか、そこらへんも全く問題ない？？

なんか最新のを入れすぎても、例えばNode.jsをBunに変えるとかはその方が早くなると思うんですけど、ちょっと怖いからやめておきたいという気持ちがあります。

そこら辺問題ないのであればpnpmで全然問題ないです

**Comment by bmthd** [comment]
パッケージマネージャーの話で、Nodeはそのまま使います。
ぜひ使いましょう！

**Comment by developerhost** [comment]
@bmthd ビルドコマンドの書き換えが必要ですよね
そこら辺なんか辺なところでハマったりしないかちょっと怖いですが、やってみますか！

PR作ってもらえると嬉しいです

**Comment by developerhost** [comment]
あとnpmじゃなくて、pnpmになりますってのはwikiかどっかにドキュメントも作って欲しいです！！

知らない人も多いと思うので、このQAの内容コピペでもいいので、みんなが理解できるようにしておきたい

**Comment by bmthd** [comment]
帰ったらやりますね
