### ISSUE TITLE
CodeRabbitの誤指摘をプロンプトで防ぐ

### ISSUE THREAD

**Issue by bmthd** [developerhost/media-swap#169]
<img width="501" alt="image" src="https://github.com/developerhost/media-swap/assets/81406938/7c301695-c353-4dbb-aded-989959e8287c">

このような明らかに誤りの指摘を防ぐため、プロンプトを修正する。
修正して欲しい内容を見つけたらこのIssueに記載してください。

**Comment by bmthd** [comment]
Linkの子要素にaタグはいらなくなった

**Comment by developerhost** [comment]
cacheのインポートは不適切です。reactモジュールからcacheをインポートすることはできません。cacheはReactの公式APIではないため、この行は削除するか、適切なモジュールからインポートする必要があります。

これは誤りを指摘してくる

**Comment by bmthd** [comment]
next/navigation

**Comment by bmthd** [comment]
4月までの知識を持ったGPT-4 turboが来るらしいので、修正要らなくなるかも

**Comment by waki285** [comment]
> 4月までの知識を持ったGPT-4 turboが来るらしいので、修正要らなくなるかも

情報は2023/4までらしいので、まだいるかも

**Comment by developerhost** [comment]
一応TwitterではApp Routerには対応してるふうに返ってくると言っている人を見ました

今からAPI使えるか確認して、model変更してみます

**Comment by bmthd** [comment]
13が出たのが2022年10月なので、App Router自体は知っているかと！
既出のやつだとServer Actionsは知らないと思う
- optout:
use server,form action

これ書き足した方が良さそう

**Comment by bmthd** [comment]
FaSquareXTwitter
