### ISSUE TITLE
mongoDBの環境を分ける方法

### ISSUE THREAD

**Issue by developerhost** [developerhost/media-swap#19]
- [ ] mongoDBのプロジェクトを本番環境、ステージング環境、開発環境を用意する
- [ ] dockerを作成
- [ ] それぞれのエンドポイントにアクセスできるように設定する

参考

https://chat.openai.com/share/2b15360f-bb87-4e8b-9d38-e7a2ec55e680

**Comment by st-moritk** [comment]
@developerhost 
このイシューですが、個人開発環境はできたと思うので、あとはリモートの開発環境が必要だと思うのですが、
リモートの開発環境はvercelとmongodb atlasの設定を変更する必要があると思うのですが、今僕権限なくてできないですよね？
どうしましょうか？

**Comment by developerhost** [comment]
@st-moritk slackでコメントしました

**Comment by developerhost** [comment]
@st-moritk これ完了してると思うのでクローズします
