### ISSUE TITLE
商品登録ページがエラーになる

### ISSUE THREAD

**Issue by waki285** [developerhost/media-swap#190]
- [x] トップページの商品追加ボタンは `/add-listing` ではなく `/add-product` に飛ぶ
- [x] 商品名が入力されているのに入力されていないとなる
- [x] action.tsが"use server";されているためトーストを出せていない

**Comment by waki285** [comment]
すでにやっている人がいたら知らせてください

**Comment by developerhost** [comment]
https://github.com/developerhost/media-swap/pull/196

対応中だけど、諸々を修正するのは時間かかりそう

- [ ] タグのエラー
- [ ] transaction_keyのエラー
