### ISSUE TITLE
登録時刻がJTCではなくUTCになっている

### ISSUE THREAD

**Issue by bmthd** [developerhost/media-swap#251]
時間はデータベース上のdefault now()を使用しているため、コードではなくデータベースのタイムゾーンを変更する必要がある。
<img width="492" alt="image" src="https://github.com/developerhost/media-swap/assets/81406938/91c04e84-f449-408c-a79c-2e3356a3607e">

**Comment by developerhost** [comment]
@bmthd これ僕やろうかな
issue作成ありがとうございます！

**Comment by developerhost** [comment]
JTCではなく、JSTかな？

**Comment by bmthd** [comment]
そうかも！

**Comment by developerhost** [comment]
メモ

https://zenn.dev/gibjapan/articles/04dd5afde1ca79

**Comment by developerhost** [comment]
UTCでDBには保存して、取得時にJSTに変換するのがベストプラクティスっぽい

**Comment by developerhost** [comment]
src/utils/parseRelativeTime.ts

ではすでに変換ロジックがあったので、これはクローズします。

```
target = utcToZonedTime(target, timeZone);
```

(@bmthd )

**Comment by bmthd** [comment]
使う側で毎回変換嚙ますのは冗長なので、Service層で変換してしまったほうがいい気がする

**Comment by developerhost** [comment]
それ用の関数をservicesに作るってことですかね？
現状時刻表示が必要そうなのは、コメントと取引メッセージだけだと思うので、今は大丈夫かなと思います

冗長だなと思う時がくればその時に変更しましょう。
リファクタくらいの温度感

**Comment by bmthd** [comment]
まあ後回しでいいと思います

**Comment by bmthd** [comment]
変換する関数が既にあるなら嚙ますだけだけど

**Comment by developerhost** [comment]
多分すずねーうさんがライブラリ使って2~3行で変換ロジックを書いてくれてるので、とりあえずそれ使うで大丈夫そう
