### ISSUE TITLE
useCharacterLimitのvalueの削除

### ISSUE THREAD

**Issue by Yuki-Maeda-valour** [developerhost/media-swap#272]
valueが縛られて他との制御の勝手が悪いのでvalueを削除

**Comment by bmthd** [comment]
こちらのissueでまとめてできそうです

https://github.com/developerhost/media-swap/issues/271

**Comment by Yuki-Maeda-valour** [comment]
先消しといてもいいですか？

**Comment by bmthd** [comment]
消すだけだと動作に支障ありませんか？
文字数を検知する方法が無いような

**Comment by Yuki-Maeda-valour** [comment]
無限に打てるようになるのみで表示物に対しては問題ないかと思います。

**Comment by Yuki-Maeda-valour** [comment]
すみません、ちょっと浅はかな気がするのでやっぱり閉じます。
お騒がせしてすみませんでした💦💦
