### ISSUE TITLE
商品出品画面の見た目修正

### ISSUE THREAD

**Issue by developerhost** [developerhost/media-swap#68]
現状

![スクリーンショット 2023-10-26 14 26 29](https://github.com/developerhost/media-swap/assets/50170789/3c286cd3-c8b6-4cb6-a11c-4b23172e1e63)

メルカリを参考に、とりあえず現状のスキーマに追加したデータも登録できるようにして欲しい

![screencapture-jp-mercari-sell-create-2023-10-26-14_26_46](https://github.com/developerhost/media-swap/assets/50170789/62352165-1754-4fcb-b4ee-65121c2a2518)

inputフィールドだけ追加してデータ登録できるようにしてくれたら良いです

**Comment by bmthd** [comment]
スキーマコミット前からanyにしててProduct型に合うように情報が設定されていない影響で商品の追加ができなかったので、併せてProduct型の全てのカラムを埋めて商品を追加できるようして欲しいです。
例えば、ユーザーの情報が欠如いるのでこれはログイン中のユーザーをセッションから取得する必要がありそうです

**Comment by developerhost** [comment]
@bmthd 確かに
全てのProductにそれやるの大変なんで、それなら今のProductデータ全部削除しちゃって作り直していいですか？

**Comment by bmthd** [comment]
@developerhost データベース上のデータの話ではなく、add-productのコードの型の話です

**Comment by developerhost** [comment]
@bmthd なるほど
それは @herostudy1 さんにやってもらう予定です！

**Comment by developerhost** [comment]
@bmthd 今商品の追加をしたいなら直接mongoDBを書き換えるか、今でもローカルのmongoDBを用意すること自体は可能だと思うので、そこで以前のprisma.schemaに戻して追加できる状態に修正して追加するとかですかね？

間違ったこと言ってたらごめんなさい

**Comment by Yuki-Maeda-valour** [comment]
僕の確認ミスなのでもう一度作り直します。

**Comment by developerhost** [comment]
@Yuki-Maeda-valour これって一旦このissueはcloseしていいですかね？？

**Comment by Yuki-Maeda-valour** [comment]
@developerhost 
すみません、閉じて大丈夫です！
ありがとうございます😊
