### ISSUE TITLE
データベースの設計を行う

### ISSUE THREAD

**Issue by developerhost** [developerhost/media-swap#72]
- キャンセル処理
- 商品購入
- 発送中
- 受け取り完了
- 取引完了

など

画面遷移図とデータモデル図などを作成して欲しい

参考はメルカリ

**Comment by bmthd** [comment]
![ERD](https://github.com/developerhost/media-swap/assets/81406938/0f0c319c-9a6f-40a3-86f3-59a081e04280)

@developerhost データベース設計が完成しました。
確認お願いします。

**Comment by developerhost** [comment]
@bmthd あ、なるほど
これだと何にもわからないので、prisma.schemaをPRとして出してもらいたいです。
コメントとかつけて

もしくはスプレッドシートとかでデータの意味とか書いてもらうか口頭で意味を聞きたいです

**Comment by developerhost** [comment]
ラベル | 項目名 | データ型 | インデックス付き | 書式/選択値など | 備考

くらい情報がないと、ちょっとわからないです、、、

**Comment by bmthd** [comment]
議事録

生年月日の情報取らない　法的に大丈夫か。
balanceの型 Int
Point クーポン　保留　使わないかも？
Point_change_events.amount floatじゃない
性別

ユーザーテーブルにis_deletedをつけるか付けないかで
論点としては削除したときに別テーブルから削除されたユーザーであることを保証させるのが大変そう

listingsテーブル　sellerやめてユーザーにする
出品コメントテーブルから既読消す
取引コメント createdAt

通知テーブル　

メールにどのカテゴリを通知するかテーブル
