### ISSUE TITLE
サイトヘッダーのレイアウトの方向性と、修正

### ISSUE THREAD

**Issue by bmthd** [developerhost/media-swap#91]
参考にしているメルカリのスクリーンショットがアプリ版となっているが、実際にはWebサイトになるため、WEB版を参考にするべきだと思われる。

![image](https://github.com/developerhost/media-swap/assets/81406938/ccf7e072-cc2b-43b1-86aa-b62dafd5cbaf)
![image](https://github.com/developerhost/media-swap/assets/81406938/72fb0997-5b56-4f57-9431-87696f968a84)

メルカリのWeb版ではサイトロゴがトップに出るようになっており、検索窓はオーバーレイで履歴と共に出る仕様になっていた。
これに倣って検索窓をオーバーレイするのかを決め、必要であれば修正を行う。

**Comment by developerhost** [comment]
ほんとですね

こっちの方が良さそうですが、メルカリと全く同じにする必要はないので、今は対応しなくても大丈夫かなと思います

サインインとサインアウトの...は分かりづらいので見た目を変更したいなと思ってます

**Comment by bmthd** [comment]
タイトルロゴと検索窓を1:1にして、その下に未ログイン時のみログイン用メニューを出すのはどうでしょうか。
現状ではログインボタンを押すのに2アクション必要なので、メルカリのように会員登録のリンクと合わせてログインも置いて1アクションにした方が良さそうです。

**Comment by developerhost** [comment]
@bmthd あと会員登録って機能は不要だと思ってます
ログインだけで両方やっちゃって問題ないはずです

**Comment by developerhost** [comment]
@bmthd これってもう対応済みですよね？
closeしていいですか？

**Comment by developerhost** [comment]
@bmthd クローズしますね
